// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itwnxndxtsbvifiryhjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0d254bmR4dHNidmlmaXJ5aGp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2MTk2NjEsImV4cCI6MjA1NDE5NTY2MX0.tE7QHUa_TVeGuZ15nk93lX6cwiu-_kh5DDUgfwodzRA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);